name: CI Pipeline
on:
  push:
    branches: main

jobs:
  # build-basic:
  #   name: Build basic image without push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       name: Check out code

  #     - uses: mr-smithers-excellent/docker-build-push@buildx
  #       name: Build Docker image
  #       with:
  #         image: mrsmithers/docker-build-push-sample
  #         registry: docker.io
  #         addLatest: true
  #         pushImage: false

    build-multi-platform:
      name: Build multi-platform image
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          name: Check out code

        - uses: mr-smithers-excellent/docker-build-push@buildx
          name: Build & push Docker image
          with:
            image: mrsmithers/docker-build-push-sample
            registry: docker.io
            platform: linux/amd64,linux/arm64,linux/arm/v7
            multiArch: true
            addLatest: false
            pushImage: false
