name: CI Pipeline
on:
  push:
    branches: main

jobs:
  build-basic:
    name: Build basic image
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build Docker image
        with:
          image: mrsmithers/docker-build-push-sample
          registry: docker.io
          addLatest: true
          pushImage: false

  build-windows:
    name: Build basic Windows image
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build Docker image
        with:
          image: mrsmithers/docker-build-push-sample
          registry: docker.io
          dockerfile: Dockerfile.windows
          pushImage: false

  build-multi-platform:
    name: Build multi-platform image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@master
        name: Build & push Docker image
        with:
          image: mrsmithers/docker-build-push-sample
          registry: docker.io
          platform: linux/amd64,linux/arm64,linux/arm/v7
          multiPlatform: true
          addLatest: false
          pushImage: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
